server:
  port: 8484
  servlet:
    context-path: /hnty/v1/pmi
logging:
  level:
    com: INFO

spring:
  application:
    name: yhh_pmi
  profiles:
    active: dev,thread
    # 配置多次注入同一类型的bean实例会覆盖原来容器中的实例
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: hntyhnty
    url: jdbc:mysql://39.98.158.241:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

##---------------------mybatis-----------------
mybatis:
  mapperLocations: classpath:mapper/**/*Mapper.xml

##---------------------mybatis-plus-----------------
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #mybatis-plus配置控制台打印完整带参数SQL语句
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1  #逻辑删除值，默认值1
      logic-notdelete-value: 0 #逻辑未删除值，默认值0

eureka:
  client:
    service-url:
      defaultZone: http://39.101.166.4:6868/eureka
  instance:
    prefer-ip-address: true